version: "2"

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./docker/db:/data/db
    environment:
      - AUTH=no
      - MONGO_INITDB_DATABASE=sugarizer
    expose:
    - 27017
      

  server:
    build:
      context: ./docker
      dockerfile: Dockerfile-server
    restart: always
    volumes:
      - ./:/sugarizer-server
      - ../:/sugarizer-certificate
      - ../sugarizer:/sugarizer-client
    depends_on:
      - mongodb
    expose:
      - 8039
      - 8080
    ports:
      - 8039:8039
      - 8080:80